repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    exclude: helm/templates/
# - repo: https://github.com/gruntwork-io/pre-commit
#   rev: v0.0.9
#   hooks:
#   - id: helmlint
# - repo: https://github.com/dnephin/pre-commit-golang
#   rev: master
#   hooks:
#     - id: go-fmt
#     - id: go-vet
#     - id: go-lint
#     - id: go-imports
#     - id: go-cyclo
#       args: [-over=15]
#     - id: validate-toml
#     - id: no-go-testing
#     - id: golangci-lint
#     - id: go-critic
#     - id: go-unit-tests
#     - id: go-build
