apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: we-road
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/
    repoURL: https://github.com/ettoreciarcia/k8s-flow
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
