firstApp:
  create: true
  appName: app1
  env: staging
  countries:
  - it
  - es
  - uk
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

secondApp:
  create: true
  appName: app2
  env: staging
  countries:
  - it
  - es
  - uk
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
