# Default values for weroad-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

firsApp:
  enabled: true
  appName: app1
  env: staging
  countries:
  - it
  - es
  - uk
