{{- if .Values.firstApp.create }}
{{ $appName := .Values.firstApp.appName }}
{{ $environment := .Values.firstApp.env }}
{{- range $country := .Values.firstApp.countries }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: we-road-{{ $country}}
  labels:
    app: {{ $appName }}-{{ $country}}
  name: {{ $appName }}-{{ $country}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appName }}-{{ $country}}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ $appName }}-{{ $country}}
    spec:
      containers:
      - image: hecha00/{{ $appName }}:latest
        name: {{ $appName }}-{{ $country}}
        env:
        - name: APP_NAME
          value: {{ $appName }}-{{ $environment }}
        - name: COUNTRY
          value: {{ $country }}
        resources: {}
status: {}
---
{{- end }}
{{- end }}
