# {{- if .Values.firstApp.autoscaling.enabled }}
# {{ $appName := .Values.firstApp.appName }}
# {{ $environment := .Values.firstApp.env }}
# {{ $minReplicas := .Values.firstApp.autoscaling.minReplicas }}
# {{ $maxReplicas := .Values.firstApp.autoscaling.maxReplicas }}
# {{ $targetCPUUtilizationPercentage := .Values.firstApp.autoscaling.targetCPUUtilizationPercentage }}
# {{ $targetMemoryUtilizationPercentage := .Values.firstApp.autoscaling.targetMemoryUtilizationPercentage }}
# {{- if .Values.firstApp.countries }}
# {{- range $country := .Values.firstApp.countries }}
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: hpa-{{ $country }}
#   labels:
#     app:  {{ $appName }}
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{ $appName }}-{{ $country }}
#   minReplicas: {{ $minReplicas }}
#   maxReplicas: {{ $maxReplicas }}
#   metrics:
#     {{- if $targetCPUUtilizationPercentage }}
#     - type: Resource
#       resource:
#         name: cpu
#         type: Utilization
#         averageUtilization: {{ $targetCPUUtilizationPercentage }}
#     {{- end }}
#     {{- if $targetMemoryUtilizationPercentage }}
#     - type: Resource
#       resource:
#         name: memory
#         averageUtilization: {{ $targetMemoryUtilizationPercentage }}
#     {{- end }}
# ---
# {{- end }}
# {{- end }}
# {{- end}}
